name: Bai03 - CI/CD Automation

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven (Test and Package)
      run: mvn -B clean package
      working-directory: ./Bai03
      
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: order-Bai03-jar
        path: Bai03/target/*.jar
        retention-days: 5
