name: Bai 07 - PR Automated Review

on:
  pull_request:
    branches: [ "main", "master" ]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Run Maven Checkstyle
      run: mvn -B checkstyle:checkstyle
      working-directory: ./Bai07
      # RẤT QUAN TRỌNG: Không để fail tiến trình ngay lập tức nếu code sai chuẩn
      # Phải để chạy tiếp để action reviewdog phía dưới có cơ hội đọc file XML và comment
      continue-on-error: true
      
    - name: Post Inline Comments for Checkstyle Errors
      uses: reviewdog/action-checkstyle@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review # Comment trực tiếp vào các dòng code bị lỗi trong Pull Request
        level: error               # Báo lỗi và làm fail status check để khoá nút Merge
        workdir: ./Bai07
        checkstyle_config: google_checks.xml
